### ISSUE TITLE
Help Needed: Trying to install open distro in existing ELK framework 7.2.0

### ISSUE THREAD

**Issue by AtulShukla281194** [opendistro-for-elasticsearch/alerting#114]
Hi,
I am trying to install alerting plugin of open distro in kibana and elastic search. 

What did I do till now :
1. Ran below commands to install plugin in kibana and elasticsearch
kibana-plugin install file:/*/opendistro-alerting-1.2.0.0.zip

elasticsearch-plugin install file:/*/opendistro_alerting-1.2.0.0.zip

Alerting plugin is installed and can be seen on kibana console. 

Then I tried creating an alert. That when the problem came. When i am trying to click on RUN button,  I get no response for request query. When checked in elastic search logs, got below error :

{"type": "server", "timestamp": "2019-10-24T14:17:39,872+0530", "level": "ERROR", "component": "c.a.o.a.MonitorRunner", "cluster.name": "ewfd
er", "node.name": "masternod23", "cluster.uuid": "R1u1scEUSqGzSsxzy0rCng", "node.id": "tgaCe99hRd-1-8FQw_2ROg",  "message": "Error loading alerts fo
r monitor: _na_" ,
"stacktrace": ["org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/exists] is unauthorized for user [_system]",
"at org.elasticsearch.xpack.core.security.support.Exceptions.authorizationError(Exceptions.java:34) ~[?:?]",

Not sure why did it use _system user to run the query, 
Please help with this??

**Comment by lucaswin-amzn** [comment]
Hi @AtulShukla281194, it appears you are using a non open source version of Elasticsearch. The version you have includes the xpack security feature. Since we are a purely opensource project we currently do not have any plans to integrate with this feature.

You can download the opensource ES 7.2.0 from [our site](https://opendistro.github.io/for-elasticsearch-docs/docs/install/) or [Elastic Co](https://www.elastic.co/downloads/past-releases/elasticsearch-oss-7-2-0) themselves.
