### ISSUE TITLE
Run the plugin only on certain nodes in a cluster

### ISSUE THREAD

**Issue by tomerilp** [opendistro-for-elasticsearch/alerting#119]
**Is your feature request related to a problem? Please describe.**
Monitors are not getting triggered when some nodes don't have the ES Alerting plugin installed.

**Describe the solution you'd like**
Allow the monitors to run only on the nodes that have the plugin installed

**Describe alternatives you've considered**
I have a cluster with 3 data nodes, 3 masters, 2 clients with Kibana installed.
I installed the ES plugin only on the client nodes, i expected the alerts to run from those nodes,
but it seems like the scheduler in even not running as i don't see any errors nor active alerts.

Version 0.10

**Comment by lucaswin-amzn** [comment]
Hi @tomerilp,

Due to the design of our system this would not be possible. When we index a monitor the documents primary shard will be allocated to a node, we call this the "owning node". This node is expected to run this monitor, we do this to ensure that if you have 20 monitors not all 20 monitors are running on a single node and can cause high resource usage. 

It appears in the scenario you are describing the documents primary shard is on a node that does not have the alerting plugin installed and therefore does not get scheduled. In order to have your use case work you might want to experiment with the `routing` parameter you can pass while creating a document. In theory if you can force the document / owning node to be one of the nodes that has the alerting plugin running. This would not eliminate issues with the alerts that are generated since those use the monitor ID as routing as well.

In general it is good practice to keep all nodes in sync and have them all run the plugins you choose to have.

**Comment by tomerilp** [comment]
> Hi @tomerilp,
> 
> Due to the design of our system this would not be possible. When we index a monitor the documents primary shard will be allocated to a node, we call this the "owning node". This node is expected to run this monitor, we do this to ensure that if you have 20 monitors not all 20 monitors are running on a single node and can cause high resource usage.
> 
> It appears in the scenario you are describing the documents primary shard is on a node that does not have the alerting plugin installed and therefore does not get scheduled. In order to have your use case work you might want to experiment with the `routing` parameter you can pass while creating a document. In theory if you can force the document / owning node to be one of the nodes that has the alerting plugin running. This would not eliminate issues with the alerts that are generated since those use the monitor ID as routing as well.
> 
> In general it is good practice to keep all nodes in sync and have them all run the plugins you choose to have.

Thank you very much for the technical details on how this plugin actually works under the hood.
I managed to make it work only on 2 nodes from many by leveraging the [Index Allocation Settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html#index-allocation-settings)

**Comment by sysword** [comment]
> Hi @tomerilp,
> 
> Due to the design of our system this would not be possible. When we index a monitor the documents primary shard will be allocated to a node, we call this the "owning node". This node is expected to run this monitor, we do this to ensure that if you have 20 monitors not all 20 monitors are running on a single node and can cause high resource usage.
> 
> It appears in the scenario you are describing the documents primary shard is on a node that does not have the alerting plugin installed and therefore does not get scheduled. In order to have your use case work you might want to experiment with the `routing` parameter you can pass while creating a document. In theory if you can force the document / owning node to be one of the nodes that has the alerting plugin running. This would not eliminate issues with the alerts that are generated since those use the monitor ID as routing as well.
> 
> In general it is good practice to keep all nodes in sync and have them all run the plugins you choose to have.

Hi @lucaswin-amzn , does " In theory if you can force the document / owning node to be one of the nodes that has the alerting plugin running. " mean just install the plugin in data node then it can work well case all shards will only  be allocated to the data node.
