### ISSUE TITLE
[BUG] - Custom webhook response need a Response string

### ISSUE THREAD

**Issue by dominiclapointe** [opendistro-for-elasticsearch/alerting#133]
**Describe the bug**
When using custom webhook, the response need to include a ResponseString. This string can be anything. The validation of the statusCode 200 is quite enough, in my opinion.

**Other plugins installed**
Alert / SQL / Security

**To Reproduce**
1. Create a destination with custom webhook
2. Make your webhook return a StatusCode 200 `return Ok();`
3. Alert is in Error state (with a grey line)
4. Change your response to `return Ok("test");`
5. Alert is working fine (with a red line)

**Expected behavior**
Shouldnt have to pass a 'random' string as a Reponse

Thank you

PS: see https://github.com/opendistro-for-elasticsearch/alerting/blob/1d730c0f2ebace04e2ad66f32e1130adbd73ceaa/notification/src/main/java/com/amazon/opendistroforelasticsearch/alerting/destination/response/DestinationHttpResponse.java#L29

**Comment by freegit9527** [comment]
when I set reponse to anything , Alert is in Error state (with a grey line). Could you show me your code?
@dominiclapointe

**Comment by kthy** [comment]
I'm seeing the same, and it's somewhat annoying. An easy way to test is to point your webhook at https://webhook.site/ which allows you to test webhooks easily. I can see my alert getting through, but then the Alerting plugin barfs on the empty response.

**Comment by f3anaro** [comment]
Hello :slightly_smiling_face: We experience the very same problem when using Slack webhooks created via Workflow Builder. The response of the Slack webhook is intentionally empty:

```bash
$  curl -v -X POST -d '{"text": "Hello world!"}'  https://hooks.slack.com/workflows/<our-web-hook>
> POST /workflows/T016M3G1GHZ/A01C9N5HMMG/323295412070922830/VcUvEMd1qsbje4QLrFyQC0jC HTTP/2
> Host: hooks.slack.com
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 24
> Content-Type: application/x-www-form-urlencoded
> 

< HTTP/2 200 
< date: Fri, 16 Oct 2020 13:57:38 GMT
< server: Apache
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-slack-backend: r
< referrer-policy: no-referrer
< vary: Accept-Encoding
< x-xss-protection: 0
< access-control-allow-origin: *
< x-frame-options: SAMEORIGIN
< content-length: 0
< content-type: application/json; charset=utf-8
< x-via: haproxy-www-lo72,haproxy-edge-dub-2jg4
```

Notification actions in index policies are failing:

| State        | Action       | Info                                         | Job Status |
| ------------ | ------------ | -------------------------------------------- | ---------- |
| hot          | notification | Failed to send notification [index=my-index] | Failed     |

with

```json
{
    "cause": "java.lang.IllegalArgumentException: Response is missing",
    "errorNotificationFailure": "java.lang.IllegalArgumentException: Response is missing",
    "message": "Failed to send notification [index=my-test-index]"
}
```

Empty responses should be allowed to enable this common workflow, especially since Slack is officially supported by OpenDistro.

**Comment by f3anaro** [comment]
Hello :slightly_smiling_face: We experience the very same problem when using Slack webhooks created via Workflow Builder. The response of the Slack webhook is intentionally empty:

```bash
$  curl -v -X POST -d '{"text": "Hello world!"}'  https://hooks.slack.com/workflows/<our-web-hook>
> POST /workflows/<our-web-hook> HTTP/2
> Host: hooks.slack.com
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 24
> Content-Type: application/x-www-form-urlencoded
> 

< HTTP/2 200 
< date: Fri, 16 Oct 2020 13:57:38 GMT
< server: Apache
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-slack-backend: r
< referrer-policy: no-referrer
< vary: Accept-Encoding
< x-xss-protection: 0
< access-control-allow-origin: *
< x-frame-options: SAMEORIGIN
< content-length: 0
< content-type: application/json; charset=utf-8
< x-via: haproxy-www-lo72,haproxy-edge-dub-2jg4
```

Notification actions in index policies are failing:

| State        | Action       | Info                                         | Job Status |
| ------------ | ------------ | -------------------------------------------- | ---------- |
| hot          | notification | Failed to send notification [index=my-index] | Failed     |

with

```json
{
    "cause": "java.lang.IllegalArgumentException: Response is missing",
    "errorNotificationFailure": "java.lang.IllegalArgumentException: Response is missing",
    "message": "Failed to send notification [index=my-test-index]"
}
```

Empty responses should be allowed to enable this common workflow, especially since Slack is officially supported by OpenDistro.
