### ISSUE TITLE
[BUG] illegal_argument_exception after migration

### ISSUE THREAD

**Issue by snarmaev** [opendistro-for-elasticsearch/alerting#173]
**Describe the bug**
After upgrade ES/Kibana to 1.4.0 we were start experiencing an issue to create monitor/trigger/destination. 
Error from the log:
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[es-node-25.company.com][10.0.0.38:9300][indices:admin/mapping/put]"}],"type":"illegal_argument_exception","reason":"mapper [monitor.schedule.period.unit] of different type, current_type [text], merged_type [keyword]"},"status":400}'

**Other plugins installed**
Security plugin

**To Reproduce**
1. Go to 'Alerting'
2. Click on 'Create monitor' or 'Create Trigger' or 'Create Destination'

**Expected behavior**
Monitor/Trigger/Destination should be created

**Screenshots**
N/A See error above

**Desktop (please complete the following information):**
 - OS: Ubuntu v4.15.0
 - Browser Chrome v79.0.3945.130 
 - Version ES/Kibana 1.4.0

**Additional context**

**Comment by dbbaughe** [comment]
Hi @snarmaev,

What version are you upgrading from?

**Comment by snarmaev** [comment]
From 1.2.1

**Comment by dbbaughe** [comment]
Could you post your .opendistro-alerting-config mappings?
I don't believe we ever had monitor.schedule.period.unit as type `text` so I'm wondering if your mappings got created dynamically somehow before the plugin could create the correct mappings.

**Comment by snarmaev** [comment]
How can I obtain this information?

**Comment by dbbaughe** [comment]
Kibana Dev Tools:
GET .opendistro-alerting-config/_mappings

Elasticsearch:
curl <es-endpoint>/.opendistro-alerting-config/_mappings?pretty

**Comment by snarmaev** [comment]
From Kibana Dev Tools:
https://justpaste.it/7hbkm

Elasticsearch:
unable to get data "no permissions for [indices:admin/mappings/get]"

**Comment by dbbaughe** [comment]
Yep, so it looks like your index was created with dynamic mappings before our plugin could create it.

Did you start using Alerting from 1.2 or have you been using from an earlier version and upgrading? I believe there was this bug in an earlier 0.x version, which was fixed.. if this happened from 1.2 then it's something we need to look in to.

You basically need to be able to recreate the index with the correct mappings. How you go about doing that is up to you, but we don't have an easy way of fixing it from our plugin. A few options depending on your usage:
1. If you aren't using the alerting plugin heavily, you could wipe the index and recreate your monitors.
2. Write a script to export your current .opendistro-alerting-config documents, delete index, recreate and import the documents
3. Reindex into different index, delete .opendistro-alerting-config, make sure index is creating with correct mappings, and reindex back.

One thing to be careful of for any of the above, if you delete the .opendistro-alerting-config index you will have the Alerting plugin clean up any alerts you have. I believe you can stop this behavior by disabling the job sweeper while doing this, but I would back up any alerts just in case. You also want to ensure you keep the same monitor document id's so they align with the alert monitor_ids.

All of these are not great options which I understand, and we plan to add an export/import tool to make things like this easier.

**Comment by snarmaev** [comment]
yes, that is correct, we tried to use alerting in version 1.2.1. However, we are not using it at all. 

So, it is ok to wipe it out. How can we wipe the indexes? Or current config?

**Comment by dbbaughe** [comment]
I see, so you did start using alerting only from 1.2.1? Any specific steps you remember doing? I can go back through commits, but I was under the impression that this bug was fixed by then.


For wiping out your current alerting configuration:

You can go on Kibana and run:
DELETE .opendistro-alerting-*

This would delete all alerting indices (monitors, destinations and alerts). Then go back to Alerting and create a test monitor. Run the previous command from Kibana Dev Tools to get the _mappings and confirm it looks like this:

https://github.com/opendistro-for-elasticsearch/alerting/blob/bc0932efa5f724f8161fca5d1e04092a27bf2b67/core/src/main/resources/mappings/scheduled-jobs.json

You should be able to quickly confirm by looking for this part:
https://github.com/opendistro-for-elasticsearch/alerting/blob/bc0932efa5f724f8161fca5d1e04092a27bf2b67/core/src/main/resources/mappings/scheduled-jobs.json#L68

You can see the query is a type object and enabled: false, if you look at your mappings and see that then you're good. If you see a bunch of mappings underneath this query object then it means you somehow got dynamic mappings again.

**Comment by snarmaev** [comment]
Awesome... It worked! Thank you so much for your help!
