### ISSUE TITLE
Support date math in index names

### ISSUE THREAD

**Issue by smowky** [opendistro-for-elasticsearch/alerting#254]
**Is your feature request related to a problem? Please describe.**
I’m using elasticsearch ILM to rotate my indexes and now alerts are searching through all indexes metricbeat-* which is quite expensive operation.
It would be nice to have a possibility to search only for last 2 day indexes instead

**Describe the solution you'd like**
Would be nice define search index as:
<logstash-{now/d-2d}>,<logstash-{now/d-1d}>,<logstash-{now/d}>
or
%3Clogstash-%7Bnow%2Fd-2d%7D%3E%2C%3Clogstash-%7Bnow%2Fd-1d%7D%3E%2C%3Clogstash-%7Bnow%2Fd%7D%3E

**Describe alternatives you've considered**
Alternative solutions is using aliases , which is be default not as easy since elasticsearch ILM actions does not have a possibility do add/remove alias

**Comment by aditjind** [comment]
Hi @smowky, 

ES already has the support built in to support Date Math Index Name Resolution to search over a range of indices. Since alerting uses the [Node Client](https://www.javadoc.io/doc/org.elasticsearch/elasticsearch/5.0.0/org/elasticsearch/client/support/AbstractClient.html#execute-org.elasticsearch.action.Action-Request-) to index and search this should be possible with-in the current implementation. 

Please check once with our latest release.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/74
