### ISSUE TITLE
Alerts needs stricter ownership

### ISSUE THREAD

**Issue by oscarkraemer** [opendistro-for-elasticsearch/alerting#302]
**Is your feature request related to a problem? Please describe.**
Alerts are hard to managed since the ownership seems to based on all the roles a user belongs to. If a user belongs to many roles then a lot of users will see the alerts that the user creates.

**Describe the solution you'd like**
Alerts should be owned by tenants and/or alerts should be tightly coupled with a specific role.

**Describe alternatives you've considered**
- Only allow users that only have one role.
- Not using alerting.

**Additional context**
Assumes that this is configured: `“opendistro.alerting.filter_by_backend_roles": "true”`

Our example organisation:
network-admins belongs to network-role
database-admins belongs to database-role
Senior-admins - belongs to network-role and database-role

In this kind of setup senior-admins can’t create an alerts that *only* network-admins have access, since all alerts senior-admin creates both network-admins and database-admins will have access to.

**Comment by skkosuri-amzn** [comment]
@oscarkraemer Thanks for creating enhancement. One way to achieve this would be - to select the roles to be associated with the monitor during create or update. Added this to the backlog.

**Comment by ryn9** [comment]
@skkosuri-amzn 

Selecting the backend to be associated with the monitor during creation and updates would be very welcome for alerting and anomaly detection, which has a similar mechanism. 

Additionally, a permission that could bypass the filter for admin and management purposes is needed. 
Currently we cannot admin/manage alerting and anomaly detection from our admin accounts, nor api calls, due to requiring the caller to be in the needed backend groups, but not additional unwanted groups. Very frustrating!

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/82
