### ISSUE TITLE
Support alerting when xpack security is enabled

### ISSUE THREAD

**Issue by AhmadMS1988** [opendistro-for-elasticsearch/alerting#331]
**Is your feature request related to a problem? Please describe.**
When trying to enable alerting on Elasticsearch with Basic license and xpack security is enabled, we get the following error:
[security_exception] action [indices:data/read/search] is unauthorized for user [_system]

**Describe the solution you'd like**
Please add support for alerting when xpack security is enabled.

**Describe alternatives you've considered**
There is no effective alternative at the moment, so please take this into consideration.

**Additional context**
Elasticsearch Native Alerting with basic license is very limited, and elastalert is not maintained anymore and is not compatible with 7.10.

**Comment by skkosuri-amzn** [comment]
@AhmadMS1988 Open Distro for Elasticsearch has built-in security and alerting, it has all features included with Apache 2.0 license. Did you consider switching to Open Distro for Elasticsearch ?

**Comment by AhmadMS1988** [comment]
Actually we depends on xpack security for beats and ilm, will it be an in place replacement, and is there a way to migrate our current users to it?

**Comment by skkosuri-amzn** [comment]
Tagging @stockholmux

**Comment by skkosuri-amzn** [comment]
OpenDistro for Elasticsearch(ODFE) comes with [ISM](https://opendistro.github.io/for-elasticsearch-docs/docs/ism/). 
You can use beats to send to ODFE securely.

**Comment by AhmadMS1988** [comment]
Thank you for your response.
The main problem is that I do not know what would be the behavior or basic license beats and apm when all of these components are used.
It would be very appreciated to add xpack security compatibility since there is no alternative.
Best

**Comment by stockholmux** [comment]
@AhmadMS1988 I hear you on this, unfortunately I don't think we'll be able to support your enhancement request. We have our hands full with current roadmap and supporting xpack/elastic basic license interoperability would multiply the work.

**Comment by martinfrancois** [comment]
@stockholmux I can see your point, but then I would argue that you would need to also change the [page on the individual plugins](https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/) to say that the security plugin is required to use the alerting plugin.

We have a similar situation, where we are not using the security plugin, simply because we don't need that level of control, and without it, we cannot do anything in the alerting plugin, not even with a `superuser` role. I understand that it's not in the scope to make X-Pack individual role support working, but would it be asked much if it was possible to use the plugin with `superuser` role without the security plugin installed?

**Comment by skkosuri-amzn** [comment]
Open Distro Security plugin is not required to use Open Distro alerting plugin, though it's generally recommended to use Open Distro Security plugin.  You should be able to use alerting plugin without security, if you are seeing any error please let us know the error and stacktrace.

**Comment by liabio** [comment]
Your meaning is  can use the  Open Distro alerting plugin without a Open Distro  Security plugin, but xpack must be turned off? "[security_exception] action [indices:data/read/search] is unauthorized for user [_system] exception" will go？
